bugreport/bugreport/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tracker/', include('tracker.urls')),
    path('', RedirectView.as_view(url='tracker/')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bugreport/tracker/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.BugListView.as_view(), name='bugs'),
    path('<str:project>', views.BugListView.as_view(), name='bugs'),
    path('bugs/', views.BugListView.as_view(), name='bugs'),
    path('bugs/<str:project>/', views.BugListView.as_view(), name='bugs'),
    path('bug/<int:pk>/', views.BugDetailView.as_view(), name='bug-detail'),
    path('bug/<int:pk>/<str:project>/', views.BugDetailView.as_view(), name='bug-detail'),
    path('bug/create/', views.BugCreate.as_view(), name='bug-create'),
    path('bug/create/<str:project>/', views.BugCreate.as_view(), name='bug-create'),
    path('bug/<str:uuid>/update/', views.BugUpdate.as_view(), name='bug-update'),
    path('bug/<str:uuid>/<str:project>/update/', views.BugUpdate.as_view(), name='bug-update'),
    path('bug/track/', views.track_ticket, name='bug-track-ticket'),
    path('bug/track/<str:project>/', views.track_ticket, name='bug-track-ticket'),
]

bugreport/tracker/models.py
from django.db import models
from django.urls import reverse # Used to generate URLs by reversing the URL patterns
import uuid # Required for unique book instances
from django.utils import timezone

PROJECT = (
    ('cmm', 'CheckMyMetal'),
    ('o', 'General'),
)

class Bug(models.Model):
    """Model representing a bug."""
    ticket_number = models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular bug')
    created_at = models.DateField(default=timezone.now)

    project = models.CharField(
        max_length=10,
        choices=PROJECT,
        blank=False,
        help_text='Project where bug is occuring',
    )

    description = models.TextField(max_length=1000, help_text='Enter a brief description of the bug')

    first_name = models.CharField(max_length=100, null=True, blank=True)
    last_name = models.CharField(max_length=100, null=True, blank=True)
    affiliation = models.CharField(max_length=200, null=True, blank=True, help_text='Institution')

    LOCATION = (
        ('us', 'United States'),
        ('c', 'Canada'),
        ('m', 'Mexico'),
        ('a', 'Africa'),
        ('as', 'Asia'),
        ('e', 'Europe'),
        ('o', 'Oceania'),
        ('sa', 'South America'),
    )

    location = models.CharField(
        max_length=2,
        choices=LOCATION,
        null=True,
        blank=True,
        default='us',
    )

    email = models.EmailField(max_length=254, null=True, blank=True)

    QUERY_TYPE = (
        ('b', 'bug'),
        ('q', 'question'),
        ('s', 'suggestion'),
        ('f', 'feedback'),
        ('l', 'like'),
        ('d', 'dislike'),
        ('o', 'other'),
    )

    query_type = models.CharField(
        max_length=1,
        choices=QUERY_TYPE,
        null=True,
        blank=True,
        default='b',
    )

    screenshot_or_attachment = models.FileField(upload_to ='uploads/', help_text = "Upload screenshot or a problematic data file", null=True, blank=True)

    STATUS_TYPE = (
        ('nf', 'Not fixed'),
        ('f', 'Fixed'),
        ('pf', 'Partially fixed'),
    )

    status = models.CharField(max_length=2, choices=STATUS_TYPE, default='nf', help_text='Select a status for this bug')
    date_fixed = models.DateField('Fixed', null=True, blank=True)

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('bug-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return self.description

bugreport/tracker/forms.py
from django import forms
from .models import Bug

class TrackTicketForm(forms.Form):

    # class Meta:
    #     model = Bug
    #     fields = ('ticket_number', )
    ticket_number = forms.UUIDField()

bugreport/tracker/views.py
from django.shortcuts import render, redirect
from .models import Bug
from .models import PROJECT
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .forms import TrackTicketForm
from django.core.mail import send_mail

def index(request):
    """View function for home page of site."""

    bug_list = Bug.objects.all()
    context = {
        'bug_list': bug_list,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)

class BugListView(generic.ListView):
    model = Bug
    paginate_by = 15

    def get_context_data(self, **kwargs):
        context = super(BugListView, self).get_context_data(**kwargs)
        if 'project' in self.kwargs:
            context["project"] = self.kwargs['project']
            context["project_full"] = [v for (k,v) in PROJECT if k == self.kwargs['project']][0]
            context["bug_list"] = Bug.objects.all().filter(project = self.kwargs['project'])
        bg = dict()
        for bug in context["bug_list"]:
            if bug.status == 'nf':
                bg[bug] = "#F62D2D"
            elif bug.status == 'pf':
                bg[bug] = "#F4F59C"
            else:
                bg[bug] = "#72D080"
        context["bg"] = bg
        return context

class BugDetailView(generic.DetailView):
    model = Bug

    def get_context_data(self, **kwargs):
        context = super(BugDetailView, self).get_context_data(**kwargs)
        if 'project' in self.kwargs:
            context["project"] = self.kwargs['project']
        return context

    def bug_detail_view(request, primary_key):
        bug = get_object_or_404(Bug, pk=primary_key)
        return render(request, 'tracker/bug_detail.html', context={'bug': bug})

def send_query_email(full_name, ticket_number, email):
    send_mail(
        'Query to ' + full_name + ' system',
        'You added a query to ' + full_name +  ' system. The ticket number is ' + ticket_number + '. You can track or edit your query by providing the ticket number.',
        'joanna_len@iwonka.med.virginia.edu',
        [email],
        fail_silently=False,
    )

class BugCreate(CreateView):
    model = Bug
    fields = ['project', 'description', 'screenshot_or_attachment', 'first_name', 'last_name', 'affiliation', 'location', 'email', 'query_type']
    initial={'project': 'o'}

    def get_context_data(self, **kwargs):
        context = super(BugCreate, self).get_context_data(**kwargs)
        if 'project' in self.kwargs:
            context["project"] = self.kwargs['project']
            context["project_full"] = [v for (k,v) in PROJECT if k == self.kwargs['project']][0]
        return context

    def form_valid(self, form):
        if 'project' in self.kwargs:
            full_name = [v for (k,v) in PROJECT if k == self.kwargs['project']][0]
            if form.instance.email != None:
                send_query_email(full_name, str(form.instance.ticket_number), form.instance.email)
            obj = form.save(commit=False)
            obj.project = self.kwargs['project']
            obj.save()
            try:
                bug = Bug.objects.get(ticket_number=obj.ticket_number)
                return redirect('bug-detail', pk=bug.id, project=bug.project)
            except Bug.DoesNotExist:
                return redirect('/')
        else:
            full_name = [v for (k,v) in PROJECT if k == form.instance.project][0]
            if form.instance.email != None:
                send_query_email(full_name, str(form.instance.ticket_number), form.instance.email)
        # call the parents class method
        return super().form_valid(form)

def track_ticket(request, project=None):
    context = {}

    if request.method == 'POST':
        form = TrackTicketForm(request.POST)
        bug_found = Bug.objects.filter(ticket_number = request.POST['ticket_number'])
        if bug_found.exists():
            if project != None and bug_found.get().project == project:
                return redirect('bug-update', request.POST['ticket_number'], project)
            else:
                return redirect('bug-update', request.POST['ticket_number'])
        else:
            form = TrackTicketForm()
            form.error = "A query with given ticket number does not exist!"
    else:
        form = TrackTicketForm()

    context['form'] = form
    if project != None:
        context['project'] = project
        context["project_full"] = [v for (k,v) in PROJECT if k == project][0]
    return render(request, 'tracker/track_ticket.html', context=context)

class BugUpdate(UpdateView):
    model = Bug
    fields = ['project', 'description', 'screenshot_or_attachment', 'first_name', 'last_name', 'affiliation', 'location', 'email', 'query_type']

    def get_object(self, queryset=None):
        obj = Bug.objects.get(ticket_number=self.kwargs['uuid'])
        return obj

    def get_context_data(self, **kwargs):
        context = super(BugUpdate, self).get_context_data(**kwargs)
        context['bug'] = self.get_object()
        if 'project' in self.kwargs:
            context["project"] = self.kwargs['project']
            context["project_full"] = [v for (k,v) in PROJECT if k == self.kwargs['project']][0]
        return context

    def get_template_names(self):
        self.template_name_suffix = '_form_track'
        return super(BugUpdate, self).get_template_names()

bugreport/tracker/templates/tracker/bug_detail.html
{% extends project|yesno:'base_generic_project.html,base_generic.html' %}

{% block content %}
  <p>Bug reported at {{ bug.created_at }}</p>
  <p>Description: {{ bug.description }}</p>
  <p>The ticket number of your bug is {{ bug.ticket_number }}. Save this number in order to edit bug later.</p>
  <p>If email was provided, a copy will be sent to your email.</p>
{% endblock %}

bugreport/tracker/templates/tracker/bug_form.html
{% extends project|yesno:'base_generic_project.html,base_generic.html' %}

{% block content %}
<h3>Report the problem that you encountered {% if project_full %}in {{project_full}}{%else%}{% endif%}</h3>
<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {% if project_full %}<div style="display:none;">{{form.project}}</div>{%else%}
  <table>
    <tbody>
      <tr>
        <th><label for="id_project">Project<span style="color:red">*</span></label></th>
      </tr>
      <tr>
        <td>{{form.project}}</td>
      </tr>
    </tbody>
  </table>
  {% endif%}
  <br>
  <table class="query_type">
    <tbody>
      <tr>
        <th><label for="id_query_type">Query type</label></th>
      </tr>
      <tr>
        <td>{{form.query_type}}</td>
      </tr>
    </tbody>
  </table>
  <br>
  <table>
    <tbody>
      <tr>
        <th><label for="id_description">Description<span style="color:red">*</span></label></th>
      </tr>
      <tr>
        <td>{{form.description}}</td>
      </tr>
      <tr>
        <th><label for="id_screenshot_or_attachment">Screenshot or attachment</label></th>
      </tr>
      <tr>
        <td>{{form.screenshot_or_attachment}}</td>
      </tr>
    </tbody>
  </table>
  <br>
  <table>
    <tbody>
      <tr>
        <th><label for="id_email">Email</label></th>
      </tr>
      <tr>
        <td>{{form.email}}<br><span style="color:#878787">If you provide email, a copy of your query will be sent to you.</span></td>
      </tr>
    </tbody>
  </table>
  <br>
  <table>
    <tbody>
      <tr>
        <th><label for="id_first_name">Firstname</label></th>
        <th><label for="id_last_name">Lastname</label></th>
        <th><label for="id_affiliation">Affiliation</label></th>
        <th><label for="id_location">LOCATION</label></th>
      </tr>
      <tr>
        <td>{{form.first_name}}</td>
        <td>{{form.last_name}}</td>
        <td>{{form.affiliation}}</td>
        <td>{{form.location}}</td>
      </tr>
    </tbody>
  </table>
  <p style="color:#878787">You can provide your personal information, but it is not necessary. They will not be publically available.</p>

  <br>
  <input type="submit" value="Submit">
</form>
{% endblock %}

bugreport/tracker/templates/tracker/bug_form_project.html
{% extends "base_generic_project.html" %}

{% block content %}
<h3>Report the problem that you encountered in {{project_full}}</h3>
<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <table class="query_type">
    <tbody>
      <tr>
        <th><label for="id_query_type">Query type</label></th>
      </tr>
      <tr>
        <td>{{form.query_type}}</td>
      </tr>
    </tbody>
  </table>
  <br>
  <table>
    <tbody>
      <tr>
        <th><label for="id_description">Description<span style="color:red">*</span></label></th>
      </tr>
      <tr>
        <td>{{form.description}}</td>
      </tr>
      <tr>
        <th><label for="id_screenshot_or_attachment">Screenshot or attachment</label></th>
      </tr>
      <tr>
        <td>{{form.screenshot_or_attachment}}</td>
      </tr>
    </tbody>
  </table>
  <br>
  <table>
    <tbody>
      <tr>
        <th><label for="id_email">Email</label></th>
      </tr>
      <tr>
        <td>{{form.email}}<br><span style="color:#878787">If you provide email, a copy of your query will be sent to you.</span></td>
      </tr>
    </tbody>
  </table>
  <br>
  <table>
    <tbody>
      <tr>
        <th><label for="id_first_name">Firstname</label></th>
        <th><label for="id_last_name">Lastname</label></th>
        <th><label for="id_affiliation">Affiliation</label></th>
        <th><label for="id_location">LOCATION</label></th>
      </tr>
      <tr>
        <td>{{form.first_name}}</td>
        <td>{{form.last_name}}</td>
        <td>{{form.affiliation}}</td>
        <td>{{form.location}}</td>
      </tr>
    </tbody>
  </table>
  <p style="color:#878787">You can provide your personal information, but it is not necessary.</p>

  <br>
  <input type="submit" value="Submit">
</form>

{% endblock %}

bugreport/tracker/templates/tracker/bug_form_track.html
{% extends project|yesno:'base_generic_project.html,base_generic.html' %}

{% block content %}
<h3>The status of your ticket {{bug.ticket_number}} is {{bug.get_status_display}}</h3>
<br>
{% if bug.date_fixed %} <p>Your query is closed so it is not possible to edit it. Add new query if you need to add something. You can refer to this ticket by its ticket number.</p> {%else%}
<p>Works on your query are still in progress. You can edit it below: </p>
<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {% if project_full %}<div style="display:none;">{{form.project}}</div>{%else%}
  <table>
    <tbody>
      <tr>
        <th><label for="id_project">Project<span style="color:red">*</span></label></th>
      </tr>
      <tr>
        <td>{{form.project}}</td>
      </tr>
    </tbody>
  </table>
  {% endif%}
  <br>
  <table class="query_type">
    <tbody>
      <tr>
        <th><label for="id_query_type">Query type</label></th>
      </tr>
      <tr>
        <td>{{form.query_type}}</td>
      </tr>
    </tbody>
  </table>
  <br>
  <table>
    <tbody>
      <tr>
        <th><label for="id_description">Description<span style="color:red">*</span></label></th>
      </tr>
      <tr>
        <td>{{form.description}}</td>
      </tr>
      <tr>
        <th><label for="id_screenshot_or_attachment">Screenshot or attachment</label></th>
      </tr>
      <tr>
        <td>{{form.screenshot_or_attachment}}</td>
      </tr>
    </tbody>
  </table>
  <br>
  <table>
    <tbody>
      <tr>
        <th><label for="id_email">Email</label></th>
      </tr>
      <tr>
        <td>{{form.email}}<br><span style="color:#878787">If you provide email, a copy of your query will be sent to you.</span></td>
      </tr>
    </tbody>
  </table>
  <br>
  <table>
    <tbody>
      <tr>
        <th><label for="id_first_name">Firstname</label></th>
        <th><label for="id_last_name">Lastname</label></th>
        <th><label for="id_affiliation">Affiliation</label></th>
        <th><label for="id_location">LOCATION</label></th>
      </tr>
      <tr>
        <td>{{form.first_name}}</td>
        <td>{{form.last_name}}</td>
        <td>{{form.affiliation}}</td>
        <td>{{form.location}}</td>
      </tr>
    </tbody>
  </table>
  <p style="color:#878787">You can provide your personal information, but it is not necessary.</p>

  <br>
  <input type="submit" value="Submit">
</form>
{%endif%}
{% endblock %}

bugreport/tracker/templates/tracker/bug_list.html
{% extends project|yesno:'base_generic_project.html,base_generic.html' %}

{% block content %}
  <h2>List of problems reported {% if project_full %}in {{project_full}}{%else%}in all projects{% endif%}</h2>
  <!-- <p>Filter status: <button type="button" name="button">Fixed</button> <button type="button" name="button">Partial fixed</button> <button type="button" name="button">Not fixed</button></p> -->
  {% if bug_list %}
  <table class="list_table">
    <tr>
      <th>DATE OF BUG REPORT</th>
      {% if project_full %}{%else%}<th>PROJECT</th>{% endif%}
      <th>BUG EXPLANATION</th>
      <th>QUERY TYPE</th>
      <th>STATUS</th>
      <th>FIXED AT</th>
    </tr>
    {% for bug in bug_list %}
      <tr style="background-color: {{bg|lookup:bug}};">
        <td>{{bug.created_at }}</td>
        {% if project_full %}{%else%}<td>{{bug.get_project_display }}</td>{% endif%}
        <td>{{bug.description}}</td>
        <td>{{bug.get_query_type_display}}</td>
        <td>{{bug.get_status_display}}</td>
        <td>{{bug.date_fixed}}</td>
      </tr>
    {% endfor %}
  </table>
  {% else %}
    <p>There are no bugs.</p>
  {% endif %}

{% endblock %}

bugreport/tracker/templates/tracker/track_ticket.html
{% extends project|yesno:'base_generic_project.html,base_generic.html' %}

{% block content %}
  <h3>Enter the ticket number of the issue you want to track</h3>
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_p }}
    </table>
    <p>{{ form.error }}</p>
    <br>
    <input type="submit" value="Submit">
  </form>
{% endblock %}